### PR TITLE
New icons 02 2021

### PR DESCRIPTION
**Pull request by notlee**
**Description:**

**Checklist:**

- [x] Icons must be a single colour (black)
- [x] Icons must be square
- [x] Icons must meet a need that is not already met by a pre-existing icon
- [x] Icons should be suitable for reuse in more than 1 application
- [x] Icons should align to a 40x40 pixel grid, with 10px padding on each side
- [x] Icons should be a solid shape rather than outlines where possible
- [x] Icons should have a minimum line thickness of 2px (including negative space thickness)
- [x] Icons should have square rather than rounded corners where suitable
- [x] Icons must be SVG v1.1
- [x] Icons must have been run through an SVG compression service (such as SVGOMG)
- [x] Icon names must be made up only of lowecase a-z, or a hyphen
- [x] Icon names must include the .svg file extension

---

[Instructions on how to tests new icons with the Origami Image Service](https://github.com/Financial-Times/fticons/blob/master/contributing.md#how-to-test-an-icon-with-the-image-service)

- [x] Testing PNG conversion using Origami Image Service
- [x] Testing PNG + resizing using Origami Image Service
- [x] Testing tinting using Origami Image Service

### CODE REVIEW

**Comment by notlee** [comment]
label outline can't be tinted, perhaps because it's using a path with a stroke?

**Comment by JakeChampion** [comment]
> label outline can't be tinted, perhaps because it's using a path with a stroke?

That's likely why, yes. Origami Image Service uses only the fill option of svg-tint-stream:

https://github.com/Financial-Times/origami-image-service/blob/9b48e0dde921447ff362df7269a52dfc222b4917/lib/middleware/handle-svg.js#L34-L37


https://github.com/Financial-Times/svg-tint-stream/blob/9212dd026d7ff2e6f5d1e02f219536a86ef48384/lib/svg-tint-stream.js#L30-L31

**Comment by notlee** [comment]
Thanks, yeah I just found that and the pr that did it. Looks like a backwards compatibility think. We should probably remove this in a future major release because making icons without outlines makes them bigger
https://github.com/Financial-Times/origami-image-service/pull/43

**Comment by notlee** [comment]
waiting on design approval as I tweaked the label icons to make their point more uniform whilst recreating them without using strokes

**Review by JakeChampion — APPROVED** [review]
Nice work 😄

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v1.22.0 :tada:

**Pull request merged**
