### PR TITLE
add scroll-to icon

### PR DESCRIPTION
**Pull request by chee**
https://financialtimes.slack.com/archives/C01481FKWA2/p1606394177148800

**Josh Wade** said:
> Please can we add this icon to our set? There’s now multiple use cases for it across live blog (app & .com) and app News Feed project.
The intention is for this arrow to represent a ‘scroll-to’ link. Our current arrows inside buttons are used to: show/hide or move backward/forward through pages - hence the need for this. Thank you.

scroll-to icon

Converted to png:
arrow

Resized to 500px png:
big arrow

Tinted #ff2a50:
pink arrow

### CODE REVIEW

**Comment by JakeChampion** [comment]
We need to go through this checklist to ensure the icon will work correctly with our components and image service:

**Checklist:**

- [ ] Icons must be a single colour (black)
- [ ] Icons must be square
- [ ] Icons must meet a need that is not already met by a pre-existing icon
- [ ] Icons should be suitable for reuse in more than 1 application
- [ ] Icons should align to a 40x40 pixel grid, with 10px padding on each side
- [ ] Icons should be a solid shape rather than outlines where possible
- [] Icons should have a minimum line thickness of 2px (including negative space thickness)
- [ ] Icons should have square rather than rounded corners where suitable
- [ ] Icons must be SVG v1.1
- [ ] Icons must have been run through an SVG compression service (such as SVGOMG)
- [ ] Icons should have a bounding box of 1024.
- [ ] Icon names must be made up only of lowecase a-z, or a hyphen
- [ ] Icon names must include the .svg file extension

---

[Instructions on how to tests new icons with the Origami Image Service](https://github.com/Financial-Times/fticons/blob/master/contributing.md#how-to-test-an-icon-with-the-image-service)

- [ ] Testing PNG conversion using Origami Image Service
- [ ] Testing PNG + resizing using Origami Image Service
- [ ] Testing tinting using Origami Image Service

**Comment by chee** [comment]
wonderful news: it looks like the viewBox requirement is no longer the case in the image service, so we can use images at the size they are:

https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:edit?source=build-service&format=png&width=500

**Comment by notlee** [comment]
@chee how come we don't need the 1024 viewbox? I thought it was to do with how Cloudinary sizes/formats images. If requesting a png I think it formats as png first then scales, making the icon blury, is that not true? We should totally have documented that if we haven't already 🙈

**Comment by chee** [comment]
> @chee how come we don't need the 1024 viewbox? I thought it was to do with how Cloudinary sizes/formats images. If requesting a png I think it formats as png first then scales, making the icon blury, is that not true? We should totally have documented that if we haven't already see_no_evil

it used to be that if you blew them up through cloudinary then they'd be blurry, but i noticed while i was reading the other SVGs that that `edit` pencil has always had a viewBox of `0 0 40 40`, and it resizes just fine! i've edited the initial post here to show this arrow as a non-blurry massive png :)

**Comment by notlee** [comment]
cool, nice find :) could you update the contributing guide?

**Review by JakeChampion — APPROVED** [review]
Excellent work :-)

**Pull request merged**
