### PR TITLE
Updated tick icon for improved clarity at smaller sizes

### PR DESCRIPTION
**Pull request by JakeChampion**
|Requirement| Completed?|
|---|---|
|Icons must be a single colour (black)| ✔️|
|Icons must be square| ✔️|
|Icons must meet a need that is not already met by a pre-existing icon| Updating an already existing icon|
|Icons should be suitable for reuse in more than 1 application| ✔️|
|Icons should align to a 40x40 pixel grid, with 10px padding on each side| Not sure how to check this|
|Icons should be a solid shape rather than outlines where possible| ✔️|
|Icons should have a minimum line thickness of 2px (including negative space thickness)| ✔️|
|Icons should have square rather than rounded corners where suitable| ✔️|
|Icons must be SVG v1.1| ✔️|
|Icons must not contain any ClipPaths. This is because the conversion of SVG to PNG in v1 of the Image Service does not work if ClipPaths are present.| ✔️|
|Icons must have been run through an SVG compression service (such as SVGOMG)| ✔️|
|Icons must have been tested with the Responsive Image Service's SVG -> PNG conversion. How do I do this?| ✔️|
|Icons must have been tested with the Image Service's tinting option. How do I do this?| ✔️|
|Icons should have a bounding box of 1024. This is because of a quirk with both versions of the Image Service, whereby a conversion from SVG to PNG will be very blurry if the source SVG has a small viewBox.| ✔️|

|Testing PNG conversion using Origami Image Service:| Completed?|
|---|---|
|v1| ✔️ |
|v2| ✔️|

|Testing PNG + resizing using Origami Image Service:| Completed?|
|---|---|
|v1| ✔️|
|v2| ✔️|

|Testing tinting using Origami Image Service:| Completed?|
|---|---|
|v1| ✔️|
|v2| ✔️|

### CODE REVIEW

**Comment by alicebartlett** [comment]
Is there a reason the padding has been changed? Its no longer consistent with all of the other icons. 
screen shot 2017-06-09 at 12 10 55

**Comment by olipowell** [comment]
Ok 😔 

Our design grid is this:

screen shot 2017-06-09 at 12 41 21

The update was meant to reflect the same stroke weight as the `cross`. Stretching the icon to fill the 20px will result in inconsistent weights, sorry I didn't realise we do this.

**Comment by JakeChampion** [comment]
@olipowell Shall I close this pull-request?

**Comment by alicebartlett** [comment]
The cross in fticons looks like this. ie it is 496x496 on a 1024x1024 viewbox.
screen shot 2017-06-12 at 11 35 20

**Comment by olipowell** [comment]
padding updated and stroke thickness aligned to cross, arrows etc.

[tick.zip](https://github.com/Financial-Times/fticons/files/1068127/tick.zip)

**Pull request merged**
