### PR TITLE
Add sign-out icon

### PR DESCRIPTION
**Pull request by JakeChampion**
**Description:**
>In the Accounts team we’d like to introduce a sign out icon which we currently don’t have in our library.
>https://financialtimes.slack.com/archives/C02FU5ARJ/p1598009398003600

There’s a feature request for the "Settings and Account" subnav to have a “Sign Out” button as its otherwise quite hard to find (buried in the burger menu). So this is to allow the Sign Out link to differentiate itself from other normal section links.

Something similar to this (different image, placement up for debate etc).

image

**Checklist:**

- [x] Icons must be a single colour (black)
- [x] Icons must be square
- [x] Icons must meet a need that is not already met by a pre-existing icon
- [x] Icons should be suitable for reuse in more than 1 application
- [x] Icons should align to a 40x40 pixel grid, with 10px padding on each side
- [x] Icons should be a solid shape rather than outlines where possible
- [x] Icons should have a minimum line thickness of 2px (including negative space thickness)
- [x] Icons should have square rather than rounded corners where suitable
- [x] Icons must be SVG v1.1
- [x] Icons must have been run through an SVG compression service (such as SVGOMG)
- [x] Icons should have a bounding box of 1024.
- [x] Icon names must be made up only of lowecase a-z, or a hyphen
- [x] Icon names must include the .svg file extension

---

[Instructions on how to tests new icons with the Origami Image Service](https://github.com/Financial-Times/fticons/blob/master/contributing.md#how-to-test-an-icon-with-the-image-service)

- [x] Testing PNG conversion using Origami Image Service
- [x] Testing PNG + resizing using Origami Image Service
- [x] Testing tinting using Origami Image Service

### CODE REVIEW

**Comment by alexnaish** [comment]
@notlee who can I ask about this from the design team? It came in from Olga to my team but happy to have a chat with someone else to get this in!

**Comment by JakeChampion** [comment]
> @notlee who can I ask about this from the design team? It came in from Olga to my team but happy to have a chat with someone else to get this in!

I've asked in the #design-ops Slack channel for a review 👍

**Comment by notlee** [comment]
This icon is to make a link in the header more prominent. The prefered design team approach is not to add an icon but to make [o-header changes](https://github.com/Financial-Times/o-header/issues/376).  Concerns were raised by the team over difficultly implementing o-header changes. I'm not sure if this was o-header itself difficultly changing header markup in the project (looks like Pagekit will need updating). I will ask Alex when he's back -- let's leave this PR open for now in case we do want to revert to an icon, but hold off on releasing

**Comment by JakeChampion** [comment]
> The prefered design team approach is not to add an icon but to make [o-header changes](https://github.com/Financial-Times/o-header/issues/376).

Closing because the Design team came up with another solution

**Pull request closed without merging**
